name: Send an email
on: push

jobs:
  Email:
    runs-on: Ubuntu-latest

    steps: 
        - name: Print
          run: echo "Hello world"

        - name: Send an email
          if: ${{always()}}
          uses: dawidd6/action-send-mail@v3
          with:
            host: smtp.google.com
        # Optional port (defaults to 465)
            port: 465
            password: ${{secrets.MAIL_PASSWORD}}
            sender: devellany
            from: ${{secrets.MAIL_ADDRESS}}
            to: devellay@dico.me
            subject: mail title.
            body: Summa.
            
                    