name: Send an email
on: push

jobs:
  Email:
    runs-on: Ubuntu-latest

    steps: 
        - name: Print
          run: echo "Hello world"

        - name: Send an email
          if: ${{always()}}
          uses: dawidd6/action-send-mail@v3
          with:
            server_address: smtp.google.com
        # Optional port (defaults to 465)
            server_port: 465
            password: ${{secrets.MAIL_PASSWORD}}
            username: ${{secrets.MAIL_ADDRESS}}
            from: mohanraghul12@gmail.com
            to: mohanraghul.g@gmail.com
            subject: mail title.
            body: Summa.
            
                    