name: Send an email
on: push

jobs:
  Email:
    runs-on: Ubuntu

    steps: 
        - name: Print
          run: echo "Hello world"

    steps:
        - name: Send an email
          if: ${{always()}}
          uses: devellany/send-mailer@v1.0.2
          with:
          host: smtp.google.com
      # Optional port (defaults to 465)
          port: 465
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          from: ${{secrets.MAIL_ADDRESS}}
          to: mohanraghul.g@gmail.com
        subject: mail title.
        body: Summa
        